/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/model.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      {/* position needs to be @ the center so 0,0,0 always and scale needs to be fit in the screen */}
      <group position={[0, 0, 0]} scale={2}>
        <mesh
          geometry={nodes.jumpkit_1.geometry}
          material={materials.wraith_jumpkit_cyberninja}
        />
        <mesh
          geometry={nodes.eye_base_1.geometry}
          material={materials.wraith_eye_base}
        />
        <mesh
          geometry={nodes.head_1.geometry}
          material={materials.wraith_head}
        />
        <mesh
          geometry={nodes.body_1.geometry}
          material={materials.wraith_body_cyberninja}
        />
        <mesh
          geometry={nodes.gauntlet_1.geometry}
          material={materials.wraith_gauntlet_cyberninja}
        />
        <mesh
          geometry={nodes.helm_1.geometry}
          material={materials.wraith_helm_cyberninja}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model.glb");
